TRAIN:
  ENABLE: False
  DATASET: ssv2
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: "datasets/SSv2/"
  PATH_PREFIX: "/home/qichunyu/datasets/SSv2/extracted_frames/"
  NUM_FRAMES: 16
  CACHE: True
  PATH_CACHE_DIR: "datasets/SSv2/"
  CACHE_ONLY: True
  TRAIN_JITTER_SCALES: [448, 512]
  TRAIN_CROP_SIZE: 448
  TEST_CROP_SIZE: 448
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
  SSIM_ADAPTIVE_SAMPLING:
    ENABLED: True
    SSIM_THRESHOLD: 0.5
    FALLBACK: False
    FALLBACK_EPSILON: 0.3
    PRE_SSIM: True
    SELECT_MIN: 8
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
  PRETRAINED_MODEL: 'pretrained/TimeSformer_divST_16_448_SSv2.pyth'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 174
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_MODEL_INFO: True
OUTPUT_DIR: 'logs/SSv2_HR/ssim_only/'